-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.



-- Table polls

CREATE TABLE IF NOT EXISTS public.polls
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    shareable_id text NOT NULL UNIQUE,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    close_at timestamp with time zone NOT NULL DEFAULT (now() + '1 day'::interval),
    is_unlisted boolean DEFAULT false,
    title text COLLATE pg_catalog."default",
    options text[] COLLATE pg_catalog."default" NOT NULL,
    allow_multiple_answers boolean DEFAULT false,
    user_id uuid,
    CONSTRAINT polls_pkey PRIMARY KEY (id),
    CONSTRAINT polls_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.polls
    OWNER to postgres;

ALTER TABLE IF EXISTS public.polls
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.polls TO anon;

GRANT ALL ON TABLE public.polls TO authenticated;

GRANT ALL ON TABLE public.polls TO postgres;

GRANT ALL ON TABLE public.polls TO service_role;
CREATE POLICY "Enable read access to all users"
    ON public.polls
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);



-- Table votes

CREATE TABLE IF NOT EXISTS public.votes
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    poll_id bigint NOT NULL,
    user_id uuid,
    option text COLLATE pg_catalog."default",
    CONSTRAINT votes_pkey PRIMARY KEY (id),
    CONSTRAINT votes_poll_id_fkey FOREIGN KEY (poll_id)
        REFERENCES public.polls (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT votes_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.votes
    OWNER to postgres;

ALTER TABLE IF EXISTS public.votes
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.votes TO anon;

GRANT ALL ON TABLE public.votes TO authenticated;

GRANT ALL ON TABLE public.votes TO postgres;

GRANT ALL ON TABLE public.votes TO service_role;
CREATE POLICY "Enable read access to all users"
    ON public.votes
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);
