name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-functions.yml
      - supabase/functions.txt
      - supabase/functions/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DATABASE_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Deploy Functions
        run: while read f ; do supabase functions deploy $f ; done < supabase/functions.txt
