name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
    paths:
      - supabase/functions.txt
      - supabase/functions/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: brew install supabase/tap/supabase

      - name: Output Supabase CLI version
        run: echo "Supabase CLI version $(supabase -v)"

      - name: Link Supabase project
        run: supabase link --project-ref="${{ secrets.SUPABASE_PROJECT }}" --password="${{ secrets.SUPABASE_DATABASE_PASSWORD }}"

      - name: Deploy Functions
        run: while read f ; do supabase functions deploy $f ; done < supabase/functions.txt
